import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Sidebar } from "lucide-react";
import { SideBar } from "@/app/(protected)/components/sidebar";
import AuthProvider from "@/providers/authProvider";
import { Provider } from "react-redux";
import { persistor, store } from "@/common/store/store";
import { PersistGate } from "redux-persist/integration/react";
import { ReduxProvider } from "@/providers/reduxProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <AuthProvider>
            <div className="flex h-screen ">
              <SideBar />
              <main className="flex-1 overflow-auto transition-all duration-300 ml-0">
                <div className="p-6">{children}</div>
              </main>
            </div>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
